=== bio-mlhui/MyFramework/data_schedule/propbank-frames/frames/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>
<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>
<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*

  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
<!ELEMENT roleset (aliases?, note*, roles, usagenotes*, ( lexlinks | example | note )*)>
<!ATTLIST roleset
  id   CDATA #REQUIRED
  name CDATA #IMPLIED>
<!ELEMENT aliases (alias | argalias| mwp-descriptions)*>
<!ELEMENT alias (#PCDATA)>
<!ATTLIST alias
pos (v | n | j | l | x| m) #REQUIRED>

<!ELEMENT argalias (#PCDATA)>
<!ATTLIST argalias
pos (v | n | j | l) #REQUIRED
arg CDATA #REQUIRED>


<!--
 Multi-word predications added
-->
<!ELEMENT mwp-descriptions (syntaxdesc | mapping)*>
<!ATTLIST mwp-descriptions
id CDATA #REQUIRED>

<!ELEMENT syntaxdesc (token)*>
<!ATTLIST syntaxdesc
slots CDATA #REQUIRED>

<!ELEMENT token (#PCDATA)>
<!ATTLIST token
slot CDATA #REQUIRED
pos CDATA #REQUIRED
arg CDATA #REQUIRED
head CDATA #REQUIRED
dep CDATA #REQUIRED >

<!ELEMENT mapping (source | target)*>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>

<!ELEMENT roles   (note | role)*>
<!ELEMENT role (rolelinks)* >
<!--
  roles have a number (or an "M" associated
  with them, for common adjuncts that don't qualify for number argument status). 
  Both numbered arguments and adjuncts are labeled with the function tags from the list below:

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose
    PNC  purpose no cause (no longer used)
    CAU  cause
    CXN  constructional pattern (adjectival comparative marker)
    ADJ  adjectival (nouns only)
    COM  comitative
    DIS  discourse
    DSP  direct speech
    GOL  goal
    PAG  prototypical agent (function tag for arg1)
    PPT  prototypical patient (function tag for arg1)
    RCL  relative clause (no longer used)
    SLC  selectional constraint link
    VSP  verb specific (function tag for numbered arguments)
    LVB  light verb (for nouns only)

-->
<!ATTLIST role
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | m | M ) #REQUIRED
  f ( PAG | PPT | GOL | CXN | VSP | COM | ADJ | CAU | PRP | MNR | EXT | LOC | REC | DIR | ADV | TMP | adv | tmp | pag | ppt | gol | vsp | com | adj | cau | prp | rec | mnr | ext | loc | dir | prd | PRD ) #REQUIRED
  descr CDATA #REQUIRED>

<!ELEMENT rolelinks (rolelink)*>
<!ELEMENT rolelink (#PCDATA)>
<!ATTLIST rolelink
resource CDATA #REQUIRED
    class CDATA #REQUIRED
    version CDATA #REQUIRED>


<!ELEMENT usagenotes (usage)*>
<!ELEMENT usage EMPTY>
<!ATTLIST usage
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    inuse  CDATA #REQUIRED>

<!ELEMENT lexlinks (lexlink)*>
<!ELEMENT lexlink (#PCDATA)>
<!ATTLIST lexlink
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    class  CDATA #REQUIRED
        confidence  CDATA #REQUIRED
            src  CDATA #REQUIRED>
<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->

<!ELEMENT example (note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  src  CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>

<!-- the n and f attributes corresponds to those of the roles
     described above -->
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | m | M | a | A) #REQUIRED
  f CDATA #IMPLIED
      start CDATA #IMPLIED
        end CDATA #IMPLIED>
<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  relloc CDATA #REQUIRED>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/hypermetabolic.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="hypermetabolic">
    <roleset id="hypermetabolic.01" name="having overly high metabolism">
      <aliases>
        <alias pos="j">hypermetabolic</alias>
      </aliases>
      <roles>
        <role descr="hypermetabolic entity" f="PPT" n="1" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="-" />
      </usagenotes>
      <example name="arg1" src="medi-tmprl">
        <text>Previously described hepatic metastasis have resolved and no regions in the liver are hypermetabolic suggesting therapeutic response .</text>
        <propbank>
          <rel relloc="13">hypermetabolic</rel>
          <arg type="ARG1" start="7" end="11">no regions in the liver</arg>
          <arg type="ARGM-ADV" start="14" end="16">suggesting therapeutic response</arg>
        </propbank>
      </example>
      <note>HYPERMETABOLIC-J NOTES: Added by Julia based on medi-tmprl1to8. (from hypermetabolic.01-j)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/data_schedule/propbank-frames/frames/supratherapeutic.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="supratherapeutic">
    <roleset id="supratherapeutic.01" name="above the theraputic level">
      <aliases>
        <alias pos="j">supratherapeutic</alias>
      </aliases>
      <roles>
        <role descr="thing measuring about the theraputic level" f="PAG" n="1"/>
        <role descr="measurement" f="VSP" n="2"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
      </usagenotes>
      <example name="both args" src="medi-tmprl">
        <text>Her INR at that time was noted to be supratherapeutic at 5.7 , so her Coumadin was held .</text>
        <propbank>
          <rel relloc="9">supratherapeutic</rel>
          <arg type="ARG1" start="0" end="4">Her INR at that time</arg>
          <arg type="ARG2" start="10" end="11">at 5.7</arg>
          <arg type="ARGM-ADV" start="13" end="17">so her Coumadin was held</arg>
        </propbank>
      </example>
      <note>SUPRATHERAPEUTIC-J NOTES: Added by Julia based on medi-tmprl1to8. (from supratherapeutic.01-j)</note>
      <note>- (from supratherapeutic.01-j)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/avidity.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="avidity">
    <roleset id="avidity.01" name="eagerness for, have an eagerness for">
      <aliases>
        <alias pos="j">avid</alias>
        <alias pos="n">avidity</alias>
        <alias pos="j">avidity</alias>
      </aliases>
      <roles>
        <role descr="eager entity" f="PAG" n="0" />
        <role descr="eager for" f="PPT" n="1" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="+" />
      </usagenotes>
      <lexlinks />
      <example name="normal example" src="">
        <text>avidity for learning</text>
        <propbank>
          <rel relloc="0">avidity</rel>
          <arg type="ARG1" start="1" end="2">for learning</arg>
        </propbank>
      </example>
      <example name="medical example" src="">
        <text>A left pelvic lymph node was also PET avid</text>
        <propbank>
          <rel relloc="8">avid</rel>
          <arg type="ARG0" start="0" end="4">A left pelvic lymph node</arg>
          <arg type="ARGM-DIS" start="6" end="6">also</arg>
          <arg type="ARG1" start="7" end="7">PET</arg>
        </propbank>
      </example>
      <example name="both args" src="">
        <text>four lesions are PET - avid</text>
        <propbank>
          <rel relloc="5">avid</rel>
          <arg type="ARG0" start="0" end="1">four lesions</arg>
          <arg type="ARG1" start="3" end="3">PET</arg>
        </propbank>
      </example>
      <note>AVIDITY-J NOTES: Based on Thyme and Sharp data. No comparison. No VN or FN classes. Framed by Katie. (from avidity.01-j)</note>
      <note>AVID-J NOTES: Based on medical notes. Comparison with avidity.01-j. Framed by Katie. (from avid.01-j)</note>
      <note>AVIDITY-N NOTES: Based on Thyme and Sharp data. No comparison. No VN or FN classes. Framed by Katie. (from avidity.01-n)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/worthwhile.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="worthwhile">
    <roleset id="worthwhile.01" name="worthy of spending time on">
      <aliases>
        <alias pos="j">worthwhile</alias>
      </aliases>
      <roles>
        <role descr="worthwhile thing" f="PAG" n="1" />
        <role descr="worthy of what, if explicitly stated" f="PPT" n="2" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="-" />
      </usagenotes>
      <lexlinks />
      <example name="arg1" src="medi-tmprl">
        <text>It would be worthwhile to get a consultation from medical geneticist , and we would arrange for that .</text>
        <propbank>
          <rel relloc="3">worthwhile</rel>
          <arg type="ARGM-MOD" start="1" end="1">would</arg>
          <arg type="ARG1" start="4" end="10">to get a consultation from medical geneticist</arg>
        </propbank>
      </example>
      <example name="both args" src="">
        <text>We sometimes get lost as to what is worthwhile of our attention and what is simply wasting our time .</text>
        <propbank>
          <rel relloc="8">worthwhile</rel>
          <arg type="ARG1" start="6" end="6">what</arg>
          <arg type="ARG2" start="9" end="11">of our attention</arg>
        </propbank>
      </example>
      <note>WORTHWHILE-J NOTES: Added by Julia based on Medi-Tmprl1to8. Relation to worth.02. (from worthwhile.01-j)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/lyse.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="lyse">
    <roleset id="lyse.01" name="to cause dissolution or destruction of cells by lysins">
      <aliases>
        <alias pos="v">lyse</alias>
        <alias pos="n">lysis</alias>
        <alias pos="n">lysing</alias>
        <alias pos="j">lytic</alias>
      </aliases>
      <roles>
        <role descr="intentional agent of lysis (e.g. scientist)" f="PAG" n="0" />
        <role descr="thing distroyed" f="PPT" n="1" />
        <role descr="instrument, lysin" f="MNR" n="2" />
        <role descr="result of lysis, lysate" f="PRD" n="3" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="+" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="+" />
        <usage resource="AMR" version="THYME 1.0" inuse="+" />
      </usagenotes>
      <lexlinks />
      <example name="lyse-v: intentional agent" src="">
        <text>Thus , we lysed cells transfected with mutant SOD1 at earlier time points .</text>
        <propbank>
          <rel relloc="3">lysed</rel>
          <arg type="ARG0" start="2" end="2">we</arg>
          <arg type="ARG1" start="4" end="8">cells transfected with mutant SOD1</arg>
        </propbank>
      </example>
      <example name="lyse-v: lysate and instrument" src="">
        <text>Red blood cells were lysed from the peripheral blood samples using Immu as previously described .</text>
        <propbank>
          <rel relloc="3 4">were lysed</rel>
          <arg type="ARG3" start="0" end="2">Red blood cells</arg>
          <arg type="ARG1" start="5" end="9">from the peripheral blood samples</arg>
          <arg type="ARG2" start="10" end="11">using Immu</arg>
        </propbank>
      </example>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/data_schedule/propbank-frames/frames/overread.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="overread">
    <roleset id="overread.01" name="read again more closely, interperate to a greater degree">
      <aliases>
        <alias pos="v">overread</alias>
      </aliases>
      <roles>
        <role descr="reader" f="PAG" n="0" />
        <role descr="thing read" f="PPT" n="1" />
        <role descr="predication, read as" f="PRD" n="2" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="-" />
      </usagenotes>
      <example name="args 0 and 1" src="">
        <text>Although it seems that the left hepatic lobe lesion seen from outside was largely described as benign , we will go ahead and have both the CT as well as MRI over - read here by Texas Elks Care Center .</text>
        <propbank>
          <rel relloc="31 32 33">over - read</rel>
          <arg type="ARG1" start="24" end="30">both the CT as well as MRI</arg>
          <arg type="ARGM-LOC" start="34" end="34">here</arg>
          <arg type="ARG0" start="35" end="39">by Texas Elks Care Center</arg>
        </propbank>
      </example>
      <note>OVERREAD-V NOTES: Based on temprel data. No comparison. No VN or FN classes. Framed by Katie. (from overread.01-v)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/byline.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="byline">
    <roleset id="byline.91" name="byline">
      <aliases>
        <alias pos="n">byline</alias>
        <alias pos="n">by-line</alias>
        <alias pos="n">dateline</alias>
        <alias pos="n">date-line</alias>
      </aliases>
      <roles>
        <role descr="news organization" f="VSP" n="0" />
        <role descr="author" f="VSP" n="1" />
        <role descr="photographer, illustrator" f="VSP" n="2" />
        <role descr="translator" f="VSP" n="3" />
        <role descr="means" f="VSP" n="4" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="-" />
        <usage resource="PropBank" version="3.4" inuse="-" />
        <usage resource="AMR" version="2019" inuse="+" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="-" />
        <usage resource="AMR" version="Spatial 1.0" inuse="+" />
        <usage resource="AMR" version="THYME 1.0" inuse="+" />
      </usagenotes>
      <example name="Xinhua byline" src="">
        <text>Xinhua New Agency , Shanghai , February 10 , by wire ( reporters Jinhu Xie and Chijian Zhang )</text>
        <propbank>
          <rel relloc="9 10">by wire</rel>
          <arg end="2" start="0" type="ARG0">Xinhua New Agency</arg>
          <arg end="18" start="11" type="ARG1">( reporters Jinhu Xie and Chijian Zhang )</arg>
          <arg end="10" start="10" type="ARG4">wire</arg>
          <arg end="7" start="6" type="ARGM-TMP">February 10</arg>
          <arg end="4" start="4" type="ARGM-LOC">Shanghai</arg>
        </propbank>
      </example>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/irradiate.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="irradiate">
    <roleset id="irradiate.01" name="expose to radiation">
      <aliases>
        <alias pos="v">irradiate</alias>
        <alias pos="n">irradiation</alias>
      </aliases>
      <roles>
        <role descr="exposer" f="PAG" n="0"/>
        <role descr="thing exposed" f="PPT" n="1"/>
        <role descr="radiation" f="MNR" n="2"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="+"/>
        <usage resource="PropBank" version="2.1.5" inuse="+"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="+"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="+"/>
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks/>
      <example name="ARG1" src="ontonotes nw/wsj/09/wsj_0999">
        <text>`` The -LCB- stones -RCB- that were irradiated in the U.S. are safe , '' says John Hickey , chief of the NRC operations branch , Washington .</text>
        <propbank>
          <rel relloc="7">irradiated</rel>
          <arg type="ARG1" start="1" end="4">The -LCB- stones -RCB-</arg>
          <arg type="ARGM-LOC" start="8" end="10">in the U.S.</arg>
          <arg type="R-ARG1" start="5" end="5">that</arg>
        </propbank>
      </example>
      <example name="all args" src="">
        <text>John irradiated his underwear with weapons - grade plutonium .</text>
        <propbank>
          <rel relloc="1">irradiated</rel>
          <arg type="ARG0" start="0" end="0">John</arg>
          <arg type="ARG1" start="2" end="3">his underwear</arg>
          <arg type="ARG2" start="4" end="8">with weapons - grade plutonium</arg>
        </propbank>
      </example>
      <example name="Arg0,1" src="">
        <text>While the radioactive isotopes finding their way into pollen grains were relatively few , their irradiation of pollen from within the pollen grains was significant .</text>
        <propbank>
          <rel relloc="15">irradiation</rel>
          <arg type="ARG0" start="14" end="14">their</arg>
          <arg type="ARG1" start="16" end="22">of pollen from within the pollen grains</arg>
        </propbank>
      </example>
      <note>IRRADIATE-V NOTES: Frames file for 'irradiate' based on sentences in wsj. No Verbnet entry. (from irradiate.01-v predicate notes)</note>
      <note>IRRADIATION-N NOTES: (from irradiation.01-n)</note>
    </roleset>
  </predicate>
</frameset>
