=== bio-mlhui/MyFramework/data_schedule/propbank-frames/frames/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>
<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>
<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*

  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
<!ELEMENT roleset (aliases?, note*, roles, usagenotes*, ( lexlinks | example | note )*)>
<!ATTLIST roleset
  id   CDATA #REQUIRED
  name CDATA #IMPLIED>
<!ELEMENT aliases (alias | argalias| mwp-descriptions)*>
<!ELEMENT alias (#PCDATA)>
<!ATTLIST alias
pos (v | n | j | l | x| m) #REQUIRED>

<!ELEMENT argalias (#PCDATA)>
<!ATTLIST argalias
pos (v | n | j | l) #REQUIRED
arg CDATA #REQUIRED>


<!--
 Multi-word predications added
-->
<!ELEMENT mwp-descriptions (syntaxdesc | mapping)*>
<!ATTLIST mwp-descriptions
id CDATA #REQUIRED>

<!ELEMENT syntaxdesc (token)*>
<!ATTLIST syntaxdesc
slots CDATA #REQUIRED>

<!ELEMENT token (#PCDATA)>
<!ATTLIST token
slot CDATA #REQUIRED
pos CDATA #REQUIRED
arg CDATA #REQUIRED
head CDATA #REQUIRED
dep CDATA #REQUIRED >

<!ELEMENT mapping (source | target)*>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>

<!ELEMENT roles   (note | role)*>
<!ELEMENT role (rolelinks)* >
<!--
  roles have a number (or an "M" associated
  with them, for common adjuncts that don't qualify for number argument status). 
  Both numbered arguments and adjuncts are labeled with the function tags from the list below:

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose
    PNC  purpose no cause (no longer used)
    CAU  cause
    CXN  constructional pattern (adjectival comparative marker)
    ADJ  adjectival (nouns only)
    COM  comitative
    DIS  discourse
    DSP  direct speech
    GOL  goal
    PAG  prototypical agent (function tag for arg1)
    PPT  prototypical patient (function tag for arg1)
    RCL  relative clause (no longer used)
    SLC  selectional constraint link
    VSP  verb specific (function tag for numbered arguments)
    LVB  light verb (for nouns only)

-->
<!ATTLIST role
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | m | M ) #REQUIRED
  f ( PAG | PPT | GOL | CXN | VSP | COM | ADJ | CAU | PRP | MNR | EXT | LOC | REC | DIR | ADV | TMP | adv | tmp | pag | ppt | gol | vsp | com | adj | cau | prp | rec | mnr | ext | loc | dir | prd | PRD ) #REQUIRED
  descr CDATA #REQUIRED>

<!ELEMENT rolelinks (rolelink)*>
<!ELEMENT rolelink (#PCDATA)>
<!ATTLIST rolelink
resource CDATA #REQUIRED
    class CDATA #REQUIRED
    version CDATA #REQUIRED>


<!ELEMENT usagenotes (usage)*>
<!ELEMENT usage EMPTY>
<!ATTLIST usage
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    inuse  CDATA #REQUIRED>

<!ELEMENT lexlinks (lexlink)*>
<!ELEMENT lexlink (#PCDATA)>
<!ATTLIST lexlink
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    class  CDATA #REQUIRED
        confidence  CDATA #REQUIRED
            src  CDATA #REQUIRED>
<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->

<!ELEMENT example (note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  src  CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>

<!-- the n and f attributes corresponds to those of the roles
     described above -->
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | m | M | a | A) #REQUIRED
  f CDATA #IMPLIED
      start CDATA #IMPLIED
        end CDATA #IMPLIED>
<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  relloc CDATA #REQUIRED>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/discourse-connective.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="instead-of">
    <roleset id="instead-of.91" name="instead of, as opposed to, rather than">
      <aliases>
        <alias pos="m">instead-of</alias>
        <alias pos="m">instead</alias>
        <alias pos="m">as-opposed-to</alias>
        <alias pos="m">rather-than</alias>
        <alias pos="m">not-x-but-y</alias>
      </aliases>
      <roles>
        <role descr="this" f="VSP" n="1" />
        <role descr="instead of that" f="VSP" n="2" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="-" />
        <usage resource="PropBank" version="3.4" inuse="-" />
        <usage resource="AMR" version="2019" inuse="+" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="-" />
        <usage resource="AMR" version="Spatial 1.0" inuse="+" />
        <usage resource="AMR" version="THYME 1.0" inuse="+" />
      </usagenotes>
      <example name="family" src="instead of, in lieu of, in place of, rather than, as opposed to">
        <text>Tim went for an early morning bike ride instead of sleeping in .</text>
        <propbank>
          <arg end="7" start="0" type="ARG1">Tim went for an early morning bike ride</arg>
          <arg end="11" start="10" type="ARG2">sleeping in</arg>
        </propbank>
      </example>
      <example name="not A, but B" src="">
        <text>I 'm not angry , but disappointed .</text>
        <propbank>
          <arg end="6" start="6" type="ARG1">disappointed</arg>
          <arg end="2" start="0" type="ARG2">I 'm not</arg>
        </propbank>
      </example>
      <note>For AMR annotations.</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/data_schedule/propbank-frames/frames/sigmoid.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="sigmoid">
    <roleset id="sigmoid.01" name="in the sigmoid colon portion of the gi tract">
      <aliases>
        <alias pos="j">sigmoid</alias>
      </aliases>
      <roles>
        <role descr="region described as sigmoid" f="PPT" n="1"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
      </usagenotes>
      <lexlinks/>
      <example name="arg1" src="medi-tmprl">
        <text>I discussed the development , staging , and treatment of rectosigmoid cancer with the patient and his family members , including the need to discern whether this is truly rectal or more sigmoid , as this would affect rationale for neoadjuvant chemoradiation consideration if T3 or N1 disease is noted , versus consideration of adjuvant chemotherapy as this is more sigmoid and involves lymph nodes .</text>
        <propbank>
          <rel relloc="32">sigmoid</rel>
          <arg type="ARG1" start="26" end="26">this</arg>
          <arg type="ARGM-EXT" start="31" end="31">more</arg>
        </propbank>
      </example>
      <note>SIGMOID-J NOTES: Added by Julia based on medi-tmprl1to8. (from sigmoid.01-j)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/distribution-range.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="distribution-range">
    <roleset id="distribution-range.91" name="distribution range (incl. for a normal distribution)">
      <aliases>
        <alias pos="n">distribution-range</alias>
        <alias pos="n">distribution</alias>
        <alias pos="n">range</alias>
      </aliases>
      <roles>
        <role descr="center, mean" f="VSP" n="1" />
        <role descr="lower bound" f="VSP" n="2" />
        <role descr="upper bound" f="VSP" n="3" />
        <role descr="radius, distance from center to bounds" f="VSP" n="4" />
        <role descr="confidence that value is in range, typically a percentage, e.g. 95%" f="VSP" n="5" />
        <role descr="deviation covered by range, e.g. standard-deviation, standard-error-of-the-mean" f="VSP" n="6" />
        <role descr="type of distribution, e.g. normal-distribution" f="VSP" n="7" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="-" />
        <usage resource="PropBank" version="3.4" inuse="-" />
        <usage resource="AMR" version="2019" inuse="+" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="-" />
        <usage resource="AMR" version="Spatial 1.0" inuse="+" />
        <usage resource="AMR" version="THYME 1.0" inuse="+" />
      </usagenotes>
      <example name="center and radius" src="">
        <text>142.0 &#177; 15.7 nM</text>
        <propbank>
          <rel relloc="3">nM</rel>
          <arg end="0" start="0" type="ARG1">142.0</arg>
          <arg end="3" start="2" type="ARG4">15.7 nM</arg>
        </propbank>
      </example>
      <example name="center and bounds" src="">
        <text>a range of 16.4%-19 % ( 17.7 % being the average )</text>
        <propbank>
          <rel relloc="1">range</rel>
          <arg end="7" start="5" type="ARG1">( 17.7 %</arg>
          <arg end="7" start="5" type="ARG2">( 17.7 %</arg>
          <arg end="0" start="0" type="ARG3">a</arg>
        </propbank>
      </example>
      <example name="with confidence percentage" src="">
        <text>With 95 % confidence , 42 - 45 % of voters will vote for John Smith .</text>
        <propbank>
          <rel relloc="12">vote</rel>
          <arg end="2" start="1" type="ARG2">95 %</arg>
          <arg end="2" start="1" type="ARG3">95 %</arg>
          <arg end="2" start="1" type="ARG5">95 %</arg>
        </propbank>
      </example>
      <example name="with standard-deviation" src="">
        <text>The gestational age was determined to be 28.5 weeks &#177; 10 days ( 2 standard deviations ) .</text>
        <propbank>
          <rel relloc="2">age</rel>
          <arg end="8" start="7" type="ARG1">28.5 weeks</arg>
          <arg end="11" start="10" type="ARG4">10 days</arg>
          <arg end="16" start="12" type="ARG6">( 2 standard deviations )</arg>
        </propbank>
      </example>
      <example name="with standard-error-of-the-mean" src="">
        <text>65 &#177; 3 % ( mean &#177; SEM )</text>
        <propbank>
          <rel relloc="5">mean</rel>
          <arg end="0" start="0" type="ARG1">65</arg>
          <arg end="3" start="1" type="ARG4">&#177; 3 %</arg>
          <arg end="8" start="7" type="ARG6">SEM )</arg>
        </propbank>
      </example>
      <note>For AMR annotations.</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/relook.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="relook">
    <roleset id="relook.01" name="look at again">
      <aliases>
        <alias pos="v">relook</alias>
      </aliases>
      <roles>
        <role descr="looker" f="PAG" n="0" />
        <role descr="thing looked at/for/on" f="PPT" n="1" />
        <role descr="attribute of arg 1" f="PRD" n="2" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="+" />
      </usagenotes>
      <example name="args 0 and 1" src="">
        <text>When he sees Dr. Montoya , we will relook at this .</text>
        <propbank>
          <rel relloc="8">relook</rel>
          <arg type="ARGM-TMP" start="0" end="4">When he sees Dr. Montoya</arg>
          <arg type="ARG0" start="6" end="6">we</arg>
          <arg type="ARGM-MOD" start="7" end="7">will</arg>
          <arg type="ARG1" start="9" end="10">at this</arg>
        </propbank>
      </example>
      <note>RELOOK-V NOTES: Based on sentences in Temprel data. Comparison to look.01. No VN class. Framed by Katie. (from relook.01-v)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/hepatobiliary.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="hepatobiliary">
    <roleset id="hepatobiliary.01" name="of the liver, gall bladder and bile ducts">
      <aliases>
        <alias pos="j">hepatobiliary</alias>
      </aliases>
      <roles>
        <role descr="hepatobiliary entity" f="PPT" n="1" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="-" />
      </usagenotes>
      <lexlinks />
      <example name="hepatobiliary-j: arg1" src="">
        <text>Given her history of the hepatic abscess and percutaneous biliary catheter , we will keep watch for signs and symptoms of infection that are hepatobiliary in nature as well and continue her chronic cephalosporin prophylaxis .</text>
        <propbank>
          <rel relloc="24">hepatobiliary</rel>
          <arg type="R-ARG1" start="22" end="22">that</arg>
          <arg type="ARG1" start="17" end="21">signs and symptoms of infection</arg>
          <arg type="ARGM-ADV" start="25" end="26">in nature</arg>
          <arg type="ARGM-ADV" start="27" end="28">as well</arg>
        </propbank>
      </example>
      <note>HEPATOBILIARY-J NOTES: Added by Julia based on medi-tmprl1to8. (from hepatobiliary.01-j)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/data_schedule/propbank-frames/frames/friable.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="friable">
    <roleset id="friable.01" name="fragile, crumbly, easily broken">
      <aliases>
        <alias pos="j">friable</alias>
      </aliases>
      <roles>
        <role descr="causer of fragility" f="PAG" n="0" />
        <role descr="friable thing" f="PPT" n="1" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="+"/>
      </usagenotes>
      <lexlinks />
      <example name="arg1" src="medi-tmprl">
        <text>This is mobile and friable with blood present on the examining glove .</text>
        <propbank>
          <rel relloc="4">friable</rel>
          <arg type="ARG1" start="0" end="0">This</arg>
          <arg type="ARGM-ADV" start="5" end="11">with blood present on the examining glove</arg>
        </propbank>
      </example>
      <note>FRIABLE-J NOTES: Added by Julia based on medi-tmprl1to8. (from friable.01-j)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/backward.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="backward">
    <roleset id="backward.01" name="slow in progress, feeble-minded in some aspect">
      <aliases>
        <alias pos="j">backward</alias>
      </aliases>
      <roles>
        <role descr="entity that is slow on the uptake" f="PAG" n="1" />
        <role descr="subject that arg1 is slow in, backward on" f="PPT" n="2" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="-" />
      </usagenotes>
      <lexlinks />
      <example name="All args" src="web">
        <text>Republicans have been losing political clout and power because they are so backward on social issues .</text>
        <propbank>
          <rel relloc="12">backward</rel>
          <arg type="ARG1" start="9" end="9">they</arg>
          <arg type="ARGM-EXT" start="11" end="11">so</arg>
          <arg type="ARG2" start="13" end="15">on social issues</arg>
        </propbank>
      </example>
      <example name="Arg 2 expressed as &quot;when&quot; phrase" src="BOLT P01, parts 2,3">
        <text>My sister is a primary school teacher and teachers generally hate the tories , before all this pension business came to the surface but because they 're so backward when it comes to education .</text>
        <propbank>
          <rel relloc="28">backward</rel>
          <arg type="ARG1" start="25" end="25">they</arg>
          <arg type="ARGM-EXT" start="27" end="27">so</arg>
          <arg type="ARG2" start="29" end="33">when it comes to education</arg>
        </propbank>
      </example>
      <note>BACKWARD-J NOTES: Roleset based on instances in BOLT P01, parts 2,3. Framed by Claire. (from backward.01-j)</note>
    </roleset>
    <roleset id="backward.02" name="directed or facing backward">
      <aliases>
        <alias pos="j">backward</alias>
      </aliases>
      <roles>
        <role descr="backward facing thing" f="PPT" n="1" />
        <role descr="backward from what -- correctly oriented point of comparison" f="PPT" n="2" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="-" />
      </usagenotes>
      <lexlinks />
      <example name="All args" src="web">
        <text>That seal actually needs to keep air from entering more than oil from escaping - it 's backward from what you might expect .</text>
        <propbank>
          <rel relloc="17">backward</rel>
          <arg type="ARG1" start="15" end="15">it</arg>
          <arg type="ARG2" start="18" end="22">from what you might expect</arg>
        </propbank>
      </example>
      <note>BACKWARD-J NOTES: (from backward.02-j)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/falsify.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="falsify">
    <roleset id="falsify.01" name="to forge or misrepresent">
      <aliases>
        <alias pos="v">falsify</alias>
      </aliases>
      <roles>
        <role descr="faker, agent" f="PAG" n="0" />
        <role descr="entity falsified" f="PPT" n="1" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="+" />
        <usage resource="PropBank" version="2.1.5" inuse="+" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="+" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="+" />
        <usage resource="AMR" version="THYME 1.0" inuse="+" />
      </usagenotes>
      <lexlinks>
        <lexlink class="Forging" confidence="0.8" resource="FrameNet" src="manual+strict-conv" version="1.7" />
        <lexlink class="falsify-v.1" confidence="0.1" resource="onsense" src="annot-overlap" version="on5">3</lexlink>
      </lexlinks>
      <example name="transitive" src="">
        <text>Tony was four years older than most of his fellow cadets , and gained admission to the academy because his brother had falsified his birth certificate .</text>
        <propbank>
          <rel relloc="22">falsified</rel>
          <arg type="ARG0" start="19" end="20">his brother</arg>
          <arg type="ARG1" start="23" end="25">his birth certificate</arg>
        </propbank>
      </example>
      <note>FALSIFY-V NOTES: Frames file for 'falsify' based on survey of sentences in the WSJ corpus. (from falsify.01-v predicate notes)</note>
    </roleset>
  </predicate>
</frameset>
