=== bio-mlhui/MyFramework/data_schedule/propbank-frames/frames/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>
<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>
<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*

  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
<!ELEMENT roleset (aliases?, note*, roles, usagenotes*, ( lexlinks | example | note )*)>
<!ATTLIST roleset
  id   CDATA #REQUIRED
  name CDATA #IMPLIED>
<!ELEMENT aliases (alias | argalias| mwp-descriptions)*>
<!ELEMENT alias (#PCDATA)>
<!ATTLIST alias
pos (v | n | j | l | x| m) #REQUIRED>

<!ELEMENT argalias (#PCDATA)>
<!ATTLIST argalias
pos (v | n | j | l) #REQUIRED
arg CDATA #REQUIRED>


<!--
 Multi-word predications added
-->
<!ELEMENT mwp-descriptions (syntaxdesc | mapping)*>
<!ATTLIST mwp-descriptions
id CDATA #REQUIRED>

<!ELEMENT syntaxdesc (token)*>
<!ATTLIST syntaxdesc
slots CDATA #REQUIRED>

<!ELEMENT token (#PCDATA)>
<!ATTLIST token
slot CDATA #REQUIRED
pos CDATA #REQUIRED
arg CDATA #REQUIRED
head CDATA #REQUIRED
dep CDATA #REQUIRED >

<!ELEMENT mapping (source | target)*>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>

<!ELEMENT roles   (note | role)*>
<!ELEMENT role (rolelinks)* >
<!--
  roles have a number (or an "M" associated
  with them, for common adjuncts that don't qualify for number argument status). 
  Both numbered arguments and adjuncts are labeled with the function tags from the list below:

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose
    PNC  purpose no cause (no longer used)
    CAU  cause
    CXN  constructional pattern (adjectival comparative marker)
    ADJ  adjectival (nouns only)
    COM  comitative
    DIS  discourse
    DSP  direct speech
    GOL  goal
    PAG  prototypical agent (function tag for arg1)
    PPT  prototypical patient (function tag for arg1)
    RCL  relative clause (no longer used)
    SLC  selectional constraint link
    VSP  verb specific (function tag for numbered arguments)
    LVB  light verb (for nouns only)

-->
<!ATTLIST role
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | m | M ) #REQUIRED
  f ( PAG | PPT | GOL | CXN | VSP | COM | ADJ | CAU | PRP | MNR | EXT | LOC | REC | DIR | ADV | TMP | adv | tmp | pag | ppt | gol | vsp | com | adj | cau | prp | rec | mnr | ext | loc | dir | prd | PRD ) #REQUIRED
  descr CDATA #REQUIRED>

<!ELEMENT rolelinks (rolelink)*>
<!ELEMENT rolelink (#PCDATA)>
<!ATTLIST rolelink
resource CDATA #REQUIRED
    class CDATA #REQUIRED
    version CDATA #REQUIRED>


<!ELEMENT usagenotes (usage)*>
<!ELEMENT usage EMPTY>
<!ATTLIST usage
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    inuse  CDATA #REQUIRED>

<!ELEMENT lexlinks (lexlink)*>
<!ELEMENT lexlink (#PCDATA)>
<!ATTLIST lexlink
  resource CDATA #REQUIRED
  version CDATA #REQUIRED
    class  CDATA #REQUIRED
        confidence  CDATA #REQUIRED
            src  CDATA #REQUIRED>
<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->

<!ELEMENT example (note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  src  CDATA #IMPLIED>
<!ELEMENT text (#PCDATA)>

<!-- the n and f attributes corresponds to those of the roles
     described above -->
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n ( 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | m | M | a | A) #REQUIRED
  f CDATA #IMPLIED
      start CDATA #IMPLIED
        end CDATA #IMPLIED>
<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  relloc CDATA #REQUIRED>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/radiosensitize.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="radiosensitize">
    <roleset id="radiosensitize.01" name="make cells more senstive to radiation">
      <aliases>
        <alias pos="v">radiosensitize</alias>
      </aliases>
      <roles>
        <role descr="cause of sensitivity" f="PAG" n="0" />
        <role descr="entity becoming senstive" f="PPT" n="1" />
        <role descr="senstive to what" f="GOL" n="2" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="-" />
      </usagenotes>
      <lexlinks />
      <example name="The chemo here is causing the cells to be more susceptable to radiation." src="">
        <text>radiotherapy with radiosensitizing chemo</text>
        <propbank>
          <rel relloc="2">radiosensitizing</rel>
          <arg type="ARG0" start="3" end="3">chemo</arg>
        </propbank>
      </example>
      <note>RADIOSENSITIZE-V NOTES: Based on temprel data. Comparison to sensitize.01. No VN or FN classes. Framed by Katie. (from radiosensitize.01-v)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/have-role.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="have-org-role">
    <roleset id="have-org-role.91" name="X is in organization Y as Z">
      <aliases>
        <alias pos="v">have-org-role</alias>
        <alias pos="v">have-organization-role</alias>
        <alias pos="v">have-organizational-role</alias>
        <alias pos="v">org-role</alias>
        <alias pos="v">have-role</alias>
      </aliases>
      <roles>
        <role descr="office holder" f="VSP" n="0" />
        <role descr="organization" f="VSP" n="1" />
        <role descr="title of office held" f="VSP" n="2" />
        <role descr="description of responsibility" f="VSP" n="3" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="-" />
        <usage resource="PropBank" version="3.4" inuse="-" />
        <usage resource="AMR" version="2019" inuse="+" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="-" />
        <usage resource="AMR" version="Spatial 1.0" inuse="+" />
        <usage resource="AMR" version="THYME 1.0" inuse="+" />
      </usagenotes>
      <example name="with organization" src="">
        <text>United Nations Secretary - General Ban Ki - moon</text>
        <propbank>
          <arg end="8" start="5" type="ARG0">Ban Ki - moon</arg>
          <arg end="1" start="0" type="ARG1">United Nations</arg>
          <arg end="4" start="2" type="ARG2">Secretary - General</arg>
        </propbank>
      </example>
      <example name="without organization" src="">
        <text>President Obama</text>
        <propbank>
          <arg end="1" start="1" type="ARG0">Obama</arg>
          <arg end="0" start="0" type="ARG2">President</arg>
        </propbank>
      </example>
      <example name="member" src="">
        <text>Spain is a member of NATO .</text>
        <propbank>
          <arg end="0" start="0" type="ARG0">Spain</arg>
          <arg end="5" start="5" type="ARG1">NATO</arg>
          <arg end="3" start="3" type="ARG2">member</arg>
        </propbank>
      </example>
      <example name="with :ARG3" src="">
        <text>He is the newspaper 's city editor , in charge of local news and assignments to reporters .</text>
        <propbank>
          <arg end="0" start="0" type="ARG0">He</arg>
          <arg end="4" start="3" type="ARG1">newspaper 's</arg>
          <arg end="6" start="5" type="ARG2">city editor</arg>
          <arg end="16" start="11" type="ARG3">local news and assignments to reporters</arg>
        </propbank>
      </example>
      <note>For AMR annotations.</note>
    </roleset>
  </predicate>
  <predicate lemma="have-rel-role">
    <roleset id="have-rel-role.91" name="A and B (of same type) are related, e.g. as family or friends">
      <aliases>
        <alias pos="v">have-rel-role</alias>
        <alias pos="v">have-relation-role</alias>
        <alias pos="v">have-relational-role</alias>
        <alias pos="v">rel-role</alias>
        <alias pos="v">have-role</alias>
      </aliases>
      <roles>
        <role descr="entity A" f="VSP" n="0" />
        <role descr="entity B" f="VSP" n="1" />
        <role descr="role of entity A (must be specified)" f="VSP" n="2" />
        <role descr="role of entity B (often left unspecified)" f="VSP" n="3" />
        <role descr="relationship basis (contract, case; rarely used)" f="VSP" n="4" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="-" />
        <usage resource="PropBank" version="3.4" inuse="-" />
        <usage resource="AMR" version="2019" inuse="+" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="-" />
        <usage resource="AMR" version="Spatial 1.0" inuse="+" />
        <usage resource="AMR" version="THYME 1.0" inuse="+" />
      </usagenotes>
      <example name="family" src="">
        <text>his mother</text>
        <propbank>
          <arg end="0" start="0" type="ARG0">his</arg>
          <arg end="0" start="0" type="ARG1">his</arg>
          <arg end="1" start="1" type="ARG2">mother</arg>
        </propbank>
      </example>
      <example name="family (both roles specified)" src="">
        <text>John and Mary are husband and wife</text>
        <propbank>
          <arg end="0" start="0" type="ARG0">John</arg>
          <arg end="2" start="2" type="ARG1">Mary</arg>
          <arg end="4" start="4" type="ARG2">husband</arg>
          <arg end="6" start="6" type="ARG3">wife</arg>
        </propbank>
      </example>
      <example name="friend" src="">
        <text>my good old friend Michael</text>
        <propbank>
          <arg end="4" start="4" type="ARG0">Michael</arg>
          <arg end="?" start="?" type="ARG1" />
          <arg end="3" start="2" type="ARG2">old friend</arg>
          <arg end="2" start="2" type="ARGM-MOD">old</arg>
        </propbank>
      </example>
      <example name="lawyer (with ARG4)" src="">
        <text>She is his lawyer in the patent infringement suit .</text>
        <propbank>
          <arg end="0" start="0" type="ARG0">She</arg>
          <arg end="0" start="0" type="ARG1">She</arg>
          <arg end="3" start="3" type="ARG2">lawyer</arg>
          <arg end="8" start="6" type="ARG4">patent infringement suit</arg>
        </propbank>
      </example>
      <example name="sister city" src="">
        <text>Berlin is a sister city of Los Angeles .</text>
        <propbank>
          <arg end="0" start="0" type="ARG0">Berlin</arg>
          <arg end="7" start="6" type="ARG1">Los Angeles</arg>
          <arg end="4" start="3" type="ARG2">sister city</arg>
        </propbank>
      </example>
      <example name="sister cities" src="">
        <text>Berlin and Los Angeles are sister cities .</text>
        <propbank>
          <arg end="0" start="0" type="ARG0">Berlin</arg>
          <arg end="3" start="2" type="ARG1">Los Angeles</arg>
          <arg end="5" start="5" type="ARG2">sister</arg>
          <arg end="5" start="5" type="ARG3">sister</arg>
        </propbank>
      </example>
      <note>For AMR annotations.</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/finetune.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="finetune">
    <roleset id="finetune.01" name="to make small adjustments">
      <aliases>
        <alias pos="v">finetune</alias>
        <alias pos="v">fine-tune</alias>
        <alias pos="n">finetuning</alias>
        <alias pos="n">fine-tuning</alias>
      </aliases>
      <roles>
        <role descr="adjuster, agent" f="PAG" n="0" />
        <role descr="entity fine-tuned" f="PPT" n="1" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="+" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="+" />
        <usage resource="AMR" version="THYME 1.0" inuse="+" />
      </usagenotes>
      <lexlinks />
      <example name="gerund" src="">
        <text>After the study , [the SEC]-1 would be willing [*-1]-2 to consider [*-2] adding new circuit breakers or fine - tuning the current ones , he added [*0*] [*T*-3] .</text>
        <propbank>
          <rel relloc="18 19 20">fine - tuning</rel>
          <arg type="ARG0" start="?" end="?">[*-2]</arg>
          <arg type="ARG1" start="21" end="23">the current ones</arg>
        </propbank>
      </example>
      <note>FINETUNE-V NOTES: Frames file for 'finetune' based on survey of sentences in the WSJ corpus. (from finetune.01-v predicate notes)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/noncircumferential.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="noncircumferential">
    <roleset id="noncircumferential.01" name="not lying around the edges of">
      <aliases>
        <alias pos="j">noncircumferential</alias>
      </aliases>
      <roles>
        <role descr="thing not lying around the edges" f="PAG" n="1"/>
        <role descr="the edges of what" f="PPT" n="2"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
      </usagenotes>
      <example name="arg1" src="">
        <text>The colonoscopy revealed a low rectal mass that was noncircumferential .</text>
        <propbank>
          <rel relloc="9">noncircumferential</rel>
          <arg type="ARG1" start="7" end="7">that</arg>
        </propbank>
      </example>
      <note>NONCIRCUMFERENTIAL-J NOTES: Added by Julia based on medi-tmprl1to8. (from noncircumferential.01-j)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/data_schedule/propbank-frames/frames/bisexual.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="bisexual">
    <roleset id="bisexual.01" name="attracted to both sexes">
      <aliases>
        <alias pos="j">bisexual</alias>
        <alias pos="j">bi</alias>
      </aliases>
      <roles>
        <role descr="entity attracted to both sexes" f="PAG" n="1"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
      </usagenotes>
      <lexlinks/>
      <example name="arg1" src="BOLT-4,5">
        <text>Nothing wrong with being bi , but just as bi 's have a taste for guys and girls , some people do n't have a taste for bi 's , if you know what I mean</text>
        <propbank>
          <rel relloc="4">bi</rel>
          </propbank>
      </example>
      <note>BISEXUAL-J NOTES: Added by Julia based on instance of 'bi' in BOLT-4,5. (from bisexual.01-j)</note>
      <note>BI-J NOTES: Automatically created by Julia as an alias file for unification. (from bi.01-j)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/data_schedule/propbank-frames/frames/revisualize.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="revisualize">
    <roleset id="revisualize.01" name="look at again">
      <aliases>
        <alias pos="v">revisualize</alias>
      </aliases>
      <roles>
        <role descr="Entity looking; see-er; visionary" f="PAG" n="0"/>
        <role descr="thing seen" f="PPT" n="1"/>
        <role descr="attribute" f="PRD" n="2"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
      </usagenotes>
      <example name="concrete example" src="">
        <text>We will proceed with a repeat colonoscopy to re - visualize the area</text>
        <propbank>
          <rel relloc="8 9 10">re - visualize</rel>
          <arg type="ARG0" start="0" end="0">We</arg>
          <arg type="ARG1" start="11" end="12">the area</arg>
        </propbank>
      </example>
      <note>REVISUALIZE-V NOTES: Based on temprel data. Comparison to visualize.01. Visualize is a member of VN class characterize-29.2-1-1. No FN class. Framed by Katie. (from revisualize.01-v)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/euvolemic.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="euvolemic">
    <roleset id="euvolemic.01" name="having a normal volume of bodily fluids">
      <aliases>
        <alias pos="j">euvolemic</alias>
      </aliases>
      <roles>
        <role descr="entity with a normal volume of fluids" f="PAG" n="1" />
        <role descr="volume measurement" f="VSP" n="2" />
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-" />
        <usage resource="PropBank" version="2.1.5" inuse="-" />
        <usage resource="PropBank" version="3.1" inuse="+" />
        <usage resource="PropBank" version="3.4" inuse="+" />
        <usage resource="AMR" version="2019" inuse="-" />
        <usage resource="PropBank" version="Flickr 1.0" inuse="+" />
        <usage resource="AMR" version="Spatial 1.0" inuse="-" />
        <usage resource="AMR" version="THYME 1.0" inuse="-" />
      </usagenotes>
      <example name="arg1" src="medi-tmprl">
        <text>If her pressures continue to be elevated , I would restart her ACE - inhibitor ; and ongoing evaluation of her volume status would seem to indicate she is euvolemic .</text>
        <propbank>
          <rel relloc="29">euvolemic</rel>
          <arg type="ARG1" start="27" end="27">she</arg>
        </propbank>
      </example>
      <note>EUVOLEMIC-J NOTES: Added by Julia based on medi-tmprl1to8. (from euvolemic.01-j)</note>
    </roleset>
  </predicate>
</frameset>

=== bio-mlhui/MyFramework/models/utils/amr/propbank-frames/frames/photocoagulate.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE frameset PUBLIC "-//PB//PropBank Frame v3.4 Transitional//EN" "http://propbank.org/specification/dtds/v3.4/frameset.dtd">
<frameset>
  <predicate lemma="photocoagulate">
    <roleset id="photocoagulate.01" name="destroy tissue with an intense laser beam">
      <aliases>
        <alias pos="v">photocoagulate</alias>
      </aliases>
      <roles>
        <role descr="doctor/surgeon" f="PAG" n="0"/>
        <role descr="patient, tissues, entity destroyed" f="PPT" n="1"/>
      </roles>
      <usagenotes>
        <usage resource="PropBank" version="1.0" inuse="-"/>
        <usage resource="PropBank" version="2.1.5" inuse="-"/>
        <usage resource="PropBank" version="3.1" inuse="+"/>
        <usage resource="PropBank" version="3.4" inuse="+"/>
        <usage resource="AMR" version="2019" inuse="-"/>
        <usage resource="PropBank" version="Flickr 1.0" inuse="+"/>
        <usage resource="AMR" version="Spatial 1.0" inuse="-"/>
        <usage resource="AMR" version="THYME 1.0" inuse="-"/>
      </usagenotes>
      <example name="photocoagulate-v: arg 1 only" src="">
        <text>This was biopsied extensively and then photocoagulated and tattooed .</text>
        <propbank>
          <rel relloc="6">photocoagulated</rel>
          <arg type="ARGM-TMP" start="5" end="5">then</arg>
          <arg type="ARG1" start="0" end="0">This</arg>
        </propbank>
      </example>
      <note>PHOTOCOAGULATE-V NOTES: Based on Temprel data. No comparison. No VN or FN classes. Framed by Katie. (from photocoagulate.01-v)</note>
    </roleset>
  </predicate>
</frameset>
